### ISSUE TITLE
Upstream features to eigenda-client

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigenda-proxy#130]
I noticed there's some stuff we're dealing with inside the eigenda-proxy which should be in the eigenda-client. Thinking we should upstream them to eigenda-client to keep the da-proxy's logic only server functionality focused. Features that could be upstreamed:
- [x] wait for confirmation depth (eigenda-client only has wait for finality or don't wait at all, and we implement logic to wait for n number of blocks for confirmation. shouldn't this be part of eigenda-client?)
- [ ] we do batch verification inside eigenda-proxy. shouldn't this be part of eigenda-client like kzg verification?

There's prob more, but this is what I can think of right now.
```[tasklist]
### Tasks
- [ ] https://github.com/Layr-Labs/eigenda-proxy/issues/187
```

**Comment by litt3** [comment]
Remaining work is captured in https://github.com/Layr-Labs/eigenda/issues/1000
